# Version v2 - First lucas preprocessing
lucas_read:
	python -c 'from pmu_breaking.ml_logic.Model2.lucas_preprocessor import read_raw_data; read_raw_data()'

lucas_perc_nans:
	python -c 'from pmu_breaking.ml_logic.Model2.lucas_preprocessor import columns_percentage_nan; columns_percentage_nan()';

lucas_create_y:
	python -c 'from pmu_breaking.ml_logic.Model2.lucas_preprocessor import create_y; create_y()';

lucas_raced:
	python -c 'from pmu_breaking.ml_logic.Model2.lucas_preprocessor import raced_races; raced_races()';

lucas_non_raced:
	python -c 'from pmu_breaking.ml_logic.Model2.lucas_preprocessor import non_raced_races; non_raced_races()';

lucas_compare_races:
	python -c 'from pmu_breaking.ml_logic.Model2.lucas_preprocessor import compare_raced_nonraced_size; compare_raced_nonraced_size()';

lucas_drop_useless:
	python -c 'from pmu_breaking.ml_logic.Model2.lucas_preprocessor import not_numeric; not_numeric()';

lucas_preprocess:
	python -c 'from pmu_breaking.ml_logic.Model2.lucas_preprocessor import preprocess; preprocess()';
